
import { Store, Category, Banner } from './types';
export const categories: Category[] = [
  {
    name: 'Fresh Food & Produce',
    imageUrl: '/Category/1.png'
  },
  {
    name: 'Dairy & Eggs',
    imageUrl: '/Category/2.png'
  },
  {
    name: 'Pantry & Groceries',
    imageUrl: '/Category/3.png'
  },
  {
    name: 'Snacks',
    imageUrl: '/Category/4.png'
  },
  {
    name: 'Beverages',
    imageUrl: '/Category/5.png'
  },
  {
    name: 'Bakery',
    imageUrl: '/Category/6.png'
  },
  {
    name: 'Frozen Foods',
    imageUrl: '/Category/7.png'
  },
  {
    name: 'Household Essentials',
    imageUrl: '/Category/8.png'
  },
  {
    name: 'Personal Care',
    imageUrl: '/Category/9.png'
  },
  {
    name: 'Baby',
    imageUrl: '/Category/10.png'
  }
];

export const banners: Banner[] = [
  {
    name: "Promotional Banner",
    imageUrl: '/Banner/1.png'
  }
];

const allProducts = [
  // This is the full list of 100 products from the previous version
  // Fresh Food & Produce (10 products)
  {
    "id": "1",
    "name": "Fresh Onion",
    "description": "Crisp and pungent onions, a staple for any kitchen.",
    "price": 35,
    "weight": "1 kg",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/1.jpg",
    "barcode": "1",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "2",
    "name": "Fresh Tomato",
    "description": "Ripe, red, and juicy tomatoes for salads and curries.",
    "price": 40,
    "weight": "1 kg",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/2.jpg",
    "barcode": "2",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "3",
    "name": "Himalayan Potato",
    "description": "Earthy and versatile potatoes, perfect for any dish.",
    "price": 42,
    "weight": "1 kg",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/3.jpg",
    "barcode": "3",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "4",
    "name": "Fresh Cauliflower",
    "description": "A single, fresh head of cauliflower.",
    "price": 25,
    "weight": "1 pc",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/4.jpg",
    "barcode": "4",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "5",
    "name": "Robusta Banana",
    "description": "A bunch of sweet and energy-rich bananas.",
    "price": 55,
    "weight": "1 dozen",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/5.jpg",
    "barcode": "5",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "6",
    "name": "Fresh Capsicum",
    "description": "Green capsicum, crunchy and fresh.",
    "price": 48,
    "weight": "500 g",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/6.jpg",
    "barcode": "6",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "7",
    "name": "Juicy Pomegranate",
    "description": "Rich in antioxidants, fresh pomegranates.",
    "price": 150,
    "weight": "1 kg",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/7.jpg",
    "barcode": "7",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "8",
    "name": "Fresh Coriander Bunch",
    "description": "Aromatic coriander leaves to garnish your dishes.",
    "price": 15,
    "weight": "100 g",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/8.jpg",
    "barcode": "8",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "9",
    "name": "Organic Ginger",
    "description": "Fresh and zesty ginger for a kick of flavor.",
    "price": 60,
    "weight": "250 g",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/9.jpg",
    "barcode": "9",
    "brand": "Organic India",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  {
    "id": "10",
    "name": "Fresh Mint Leaves",
    "description": "Cool and refreshing mint leaves for chutneys and drinks.",
    "price": 10,
    "weight": "100 g",
    "category": "Fresh Food & Produce",
    "imageUrl": "/Freshfood/10.jpg",
    "barcode": "10",
    "brand": "Local",
    "ecologicalScore": 95,
    "nutritionalScore": 95
  },
  // Dairy & Eggs (10 products)
  
  {
    "id": "11",
    "name": "Amul Gold Full Cream Milk",
    "description": "Rich, creamy, and wholesome full cream milk.",
    "price": 66,
    "weight": "1 l",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/1.jpg",
    "barcode": "8901262260107",
    "brand": "Amul",
    "ecologicalScore": 25,
    "nutritionalScore": 75
  },
  {
    "id": "12",
    "name": "Mother Dairy Classic Curd",
    "description": "Rich and creamy curd, made from pasteurized milk.",
    "price": 34,
    "weight": "400 g",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/2.jpg",
    "barcode": "8901648022169",
    "brand": "Mother Dairy",
    "ecologicalScore": 50,
    "nutritionalScore": 75
  },
  {
    "id": "13",
    "name": "Farm Fresh White Eggs",
    "description": "Pack of 6 nutritious and fresh white eggs.",
    "price": 50,
    "weight": "6 pcs",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/3.jpg",
    "barcode": "8906124370338",
    "brand": "Farm Fresh",
    "ecologicalScore": 55,
    "nutritionalScore": 85
  },
  {
    "id": "14",
    "name": "Amul Masti Buttermilk",
    "description": "Spiced buttermilk, a refreshing and healthy drink.",
    "price": 12,
    "weight": "200 ml",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/4.jpg",
    "barcode": "8901262200196",
    "brand": "Amul",
    "ecologicalScore": 50,
    "nutritionalScore": 55
  },
  {
    "id": "15",
    "name": "Nestle Milkmaid",
    "description": "Sweetened condensed milk for all your desserts.",
    "price": 147,
    "weight": "380 g",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/5.jpg",
    "barcode": "8901058021950",
    "brand": "Nestle",
    "ecologicalScore": 50,
    "nutritionalScore": 25
  },
  {
    "id": "16",
    "name": "Amul Butter",
    "description": "Classic salted butter, perfect for toast and cooking.",
    "price": 56,
    "weight": "100 g",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/6.jpg",
    "barcode": "8901262010016",
    "brand": "Amul",
    "ecologicalScore": 35,
    "nutritionalScore": 25
  },
  {
    "id": "17",
    "name": "Go Cheese Slices",
    "description": "Individually wrapped cheese slices for sandwiches.",
    "price": 165,
    "weight": "200 g",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/7.jpg",
    "barcode": "8906001020196",
    "brand": "Go",
    "ecologicalScore": 25,
    "nutritionalScore": 55
  },
  {
    "id": "18",
    "name": "Britannia Paneer",
    "description": "Fresh and soft malai paneer for your favorite dishes.",
    "price": 95,
    "weight": "200 g",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/8.jpg",
    "barcode": "8901063406025",
    "brand": "Britannia",
    "ecologicalScore": 30,
    "nutritionalScore": 60
  },
  {
    "id": "19",
    "name": "Mother Dairy Toned Milk",
    "description": "Fresh pasteurized toned milk.",
    "price": 58,
    "weight": "1 l",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/9.jpg",
    "barcode": "8901648921325",
    "brand": "Mother Dairy",
    "ecologicalScore": 50,
    "nutritionalScore": 75
  },
  {
    "id": "20",
    "name": "Brown Eggs - Cage Free",
    "description": "Pack of 6 nutritious brown eggs from cage-free hens.",
    "price": 75,
    "weight": "6 pcs",
    "category": "Dairy & Eggs",
    "imageUrl": "/Dairy-eggs/10.jpg",
    "barcode": "0011110797704",
    "brand": "Simple Truth",
    "ecologicalScore": 60,
    "nutritionalScore": 75
  },
  // Pantry & Groceries (10 products)
   {
    id: '21',
    name: 'Aashirvaad Select Sharbati Atta',
    description: 'Premium quality whole wheat flour.',
    price: 320,
    weight: '5 kg',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/1.jpg',
    barcode: '8901725121242',
    brand: 'Aashirvaad',
    ecologicalScore: 60,
    nutritionalScore: 75
  },
  {
    id: '22',
    name: 'Tata Salt',
    description: 'Iodized salt, a staple for every Indian household.',
    price: 25,
    weight: '1 kg',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/2.jpg',
    barcode: '8904043901015',
    brand: 'Tata',
    ecologicalScore: 70,
    nutritionalScore: 40
  },
  {
    id: '23',
    name: 'Fortune Sunlite Refined Sunflower Oil',
    description: 'Light and healthy sunflower oil for daily cooking.',
    price: 155,
    weight: '1 l',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/3.jpg',
    barcode: '8906007280242',
    brand: 'Fortune',
    ecologicalScore: 45,
    nutritionalScore: 20
  },
  {
    id: '24',
    name: 'Daawat Rozana Gold Basmati Rice',
    description: 'Aromatic and long-grain basmati rice for everyday meals.',
    price: 575,
    weight: '5 kg',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/4.jpg',
    barcode: '8901537006010',
    brand: 'Daawat',
    ecologicalScore: 50,
    nutritionalScore: 65
  },
  {
    id: '25',
    name: 'Tata Sampann Toor Dal',
    description: 'Unpolished toor dal, rich in protein and nutrients.',
    price: 170,
    weight: '1 kg',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/5.jpg',
    barcode: '8904043926223',
    brand: 'Tata Sampann',
    ecologicalScore: 75,
    nutritionalScore: 85
  },
  {
    id: '26',
    name: 'Maggi 2-Minute Masala Noodles',
    description: 'Instant noodles with a delicious masala flavor.',
    price: 14,
    weight: '70 g',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/6.jpg',
    barcode: '8901058000306',
    brand: 'Nestle',
    ecologicalScore: 30,
    nutritionalScore: 20
  },
  {
    id: '27',
    name: 'Kissan Fresh Tomato Ketchup',
    description: 'Sweet and tangy tomato ketchup to go with your snacks.',
    price: 120,
    weight: '950 g',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/7.jpg',
    barcode: '8901030921667',
    brand: 'Kissan',
    ecologicalScore: 50,
    nutritionalScore: 25
  },
  {
    id: '28',
    name: 'MDH Deggi Mirch',
    description: 'A unique blend of red chili peppers for a rich color.',
    price: 80,
    weight: '100 g',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/8.jpg',
    barcode: '8902167000034',
    brand: 'MDH',
    ecologicalScore: 70,
    nutritionalScore: 55
  },
  {
    id: '29',
    name: 'Quaker Oats',
    description: 'Healthy and wholesome oats for a perfect breakfast.',
    price: 195,
    weight: '1 kg',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/9.jpg',
    barcode: '8901491103800',
    brand: 'Quaker',
    ecologicalScore: 75,
    nutritionalScore: 85
  },
  {
    id: '30',
    name: 'Saffola Masala Oats - Classic Masala',
    description: 'Savory oats with a classic masala flavor.',
    price: 45,
    weight: '38 g',
    category: 'Pantry & Groceries',
    imageUrl: '/Pantry-groceries/10.jpg',
    barcode: '8901088129824',
    brand: 'Saffola',
    ecologicalScore: 55,
    nutritionalScore: 70
  },
  // Snacks (10 products)
  {
    id: '31',
    name: "Lay's India's Magic Masala Chips",
    description: 'Classic potato chips with a spicy masala twist.',
    price: 20,
    weight: '50 g',
    category: 'Snacks',
    imageUrl: '/Snacks/1.jpg',
    barcode: '8901491000789',
    brand: "Lay's",
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '32',
    name: 'Bingo! Mad Angles - Achaari Masti',
    description: 'Triangle shaped chips with a tangy pickle flavor.',
    price: 10,
    weight: '36.5 g',
    category: 'Snacks',
    imageUrl: '/Snacks/2.jpg',
    barcode: '8901725198336',
    brand: 'Bingo!',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '33',
    name: 'Too Yumm! Classic Salted Potato Chips',
    description: 'Baked potato chips, a healthier snacking option.',
    price: 20,
    weight: '52 g',
    category: 'Snacks',
    imageUrl: '/Snacks/3.jpg',
    barcode: '8906090573085',
    brand: 'Too Yumm!',
    ecologicalScore: 25,
    nutritionalScore: 35
  },
  {
    id: '34',
    name: "Haldiram's Bhujia",
    description: 'Classic savory and spicy dew bean flour snack.',
    price: 42,
    weight: '200 g',
    category: 'Snacks',
    imageUrl: '/Snacks/4.jpg',
    barcode: '8904004400069',
    brand: "Haldiram's",
    ecologicalScore: 30,
    nutritionalScore: 30
  },
  {
    id: '35',
    name: 'Kurkure Masala Munch',
    description: 'Spicy and crunchy corn puffs.',
    price: 20,
    weight: '90 g',
    category: 'Snacks',
    imageUrl: '/Snacks/5.jpg',
    barcode: '8901491100519',
    brand: 'Kurkure',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '36',
    name: 'Britannia Good Day Cashew Cookies',
    description: 'Buttery cookies filled with cashew nuts.',
    price: 40,
    weight: '200 g',
    category: 'Snacks',
    imageUrl: '/Snacks/6.jpg',
    barcode: '8901063092464',
    brand: 'Britannia',
    ecologicalScore: 50,
    nutritionalScore: 30
  },
  {
    id: '37',
    name: 'Cadbury Dairy Milk Chocolate Bar',
    description: 'Classic rich and creamy milk chocolate.',
    price: 45,
    weight: '42 g',
    category: 'Snacks',
    imageUrl: '/Snacks/7.jpg',
    barcode: '7622202398735',
    brand: 'Cadbury',
    ecologicalScore: 50,
    nutritionalScore: 20
  },
  {
    id: '38',
    name: 'Dark Fantasy Choco Fills Cookies',
    description: 'Chocolate-filled cookies for an indulgent treat.',
    price: 35,
    weight: '75 g',
    category: 'Snacks',
    imageUrl: '/Snacks/8.jpg',
    barcode: '8901725015275',
    brand: 'Sunfeast',
    ecologicalScore: 30,
    nutritionalScore: 20
  },
  {
    id: '39',
    name: 'ACT II Golden Sizzle Popcorn',
    description: 'Ready to make classic salted popcorn.',
    price: 10,
    weight: '30 g',
    category: 'Snacks',
    imageUrl: '/Snacks/9.jpg',
    barcode: '8901512564900',
    brand: 'ACT II',
    ecologicalScore: 65,
    nutritionalScore: 55
  },
  {
    id: '40',
    name: 'Parle-G Gold Biscuits',
    description: 'The original gluco-biscuit, bigger and richer.',
    price: 20,
    weight: '250 g',
    category: 'Snacks',
    imageUrl: '/Snacks/10.jpg',
    barcode: '8901719107665',
    brand: 'Parle-G',
    ecologicalScore: 50,
    nutritionalScore: 30
  },
  // Beverages (10 products)
{
    id: '41',
    name: 'Coca-Cola Zero Sugar Soft Drink',
    description: 'The classic and refreshing Coca-Cola soft drink.',
    price: 40,
    weight: '750 ml',
    category: 'Beverages',
    imageUrl: '/Beverages/1.jpg',
    barcode: '8901764112270',
    brand: 'Coca-Cola',
    ecologicalScore: 30,
    nutritionalScore: 50
  },
  {
    id: '42',
    name: 'Thums Up Soft Drink',
    description: 'The strong and fizzy toofani Thums Up.',
    price: 40,
    weight: '750 ml',
    category: 'Beverages',
    imageUrl: '/Beverages/2.jpg',
    barcode: '8901764042270',
    brand: 'Thums Up',
    ecologicalScore: 35,
    nutritionalScore: 20
  },
  {
    id: '43',
    name: 'Tropicana 100% Orange Juice',
    description: 'Pure and natural orange juice with no added sugar.',
    price: 135,
    weight: '1 l',
    category: 'Beverages',
    imageUrl: '/Beverages/3.jpg',
    barcode: '8902080013089',
    brand: 'Tropicana',
    ecologicalScore: 50,
    nutritionalScore: 65
  },
  {
    id: '44',
    name: 'Tata Tea Gold',
    description: 'A perfect blend of long leaves and CTC tea.',
    price: 510,
    weight: '1 kg',
    category: 'Beverages',
    imageUrl: '/Beverages/4.jpg',
    barcode: '8901052000906',
    brand: 'Tata Tea',
    ecologicalScore: 55,
    nutritionalScore: 75
  },
  {
    id: '45',
    name: 'Nescafe Classic Instant Coffee',
    description: 'Aromatic and strong instant coffee powder.',
    price: 320,
    weight: '200 g',
    category: 'Beverages',
    imageUrl: '/Beverages/5.jpg',
    barcode: '8901058016802',
    brand: 'Nescafe',
    ecologicalScore: 50,
    nutritionalScore: 65
  },
  {
    id: '46',
    name: 'Bournvita Health Drink',
    description: 'Chocolate flavored health drink for all ages.',
    price: 345,
    weight: '750 g',
    category: 'Beverages',
    imageUrl: '/Beverages/6.jpg',
    barcode: '7622202026522',
    brand: 'Cadbury',
    ecologicalScore: 50,
    nutritionalScore: 55
  },
  {
    id: '47',
    name: 'Red Bull Energy Drink',
    description: 'Gives you wings when you need them.',
    price: 125,
    weight: '250 ml',
    category: 'Beverages',
    imageUrl: '/Beverages/7.jpg',
    barcode: '0000901626026',
    brand: 'Red Bull',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '48',
    name: 'Bisleri Mineral Water',
    description: 'Pure and safe packaged drinking water.',
    price: 20,
    weight: '1 l',
    category: 'Beverages',
    imageUrl: '/Beverages/8.jpg',
    barcode: '8906017290033',
    brand: 'Bisleri',
    ecologicalScore: 50,
    nutritionalScore: 95
  },
  {
    id: '49',
    name: 'Real Activ 100% Mixed Fruit Juice',
    description: 'A blend of delicious fruits with no added sugar.',
    price: 140,
    weight: '1 l',
    category: 'Beverages',
    imageUrl: '/Beverages/9.jpg',
    barcode: '8901888005410',
    brand: 'Real Activ',
    ecologicalScore: 50,
    nutritionalScore: 60
  },
  {
    id: '50',
    name: 'Paper Boat Aamras Juice',
    description: 'Sweet and pulpy mango juice, just like homemade.',
    price: 30,
    weight: '200 ml',
    category: 'Beverages',
    imageUrl: '/Beverages/10.jpg',
    barcode: '8908001705448',
    brand: 'Paper Boat',
    ecologicalScore: 55,
    nutritionalScore: 45
  },
  // Bakery (10 products)
  {
    id: '51',
    name: 'Britannia 100% Whole Wheat Bread',
    description: 'Healthy and soft whole wheat bread.',
    price: 50,
    weight: '400 g',
    category: 'Bakery',
    imageUrl: '/Bakery/1.jpg',
    barcode: '8901063338593',
    brand: 'Britannia',
    ecologicalScore: 65,
    nutritionalScore: 75
  },
  {
    id: '52',
    name: 'The Health Factory Zero Maida Brown Bread',
    description: 'High-protein, multi-grain brown bread.',
    price: 55,
    weight: '400 g',
    category: 'Bakery',
    imageUrl: '/Bakery/2.jpg',
    barcode: '8908009059154',
    brand: 'The Health Factory',
    ecologicalScore: 45,
    nutritionalScore: 75
  },
  {
    id: '53',
    name: 'English Oven Garlic Bread',
    description: 'Ready to toast garlic bread for a quick snack.',
    price: 60,
    weight: '150 g',
    category: 'Bakery',
    imageUrl: '/Bakery/3.jpg',
    barcode: '8906001387947',
    brand: 'English Oven',
    ecologicalScore: 50,
    nutritionalScore: 40
  },
  {
    id: '54',
    name: 'Britannia Treat Cocoa Creme Croissant',
    description: 'A buttery and flaky creme filled croissant.',
    price: 75,
    weight: '45 g',
    category: 'Bakery',
    imageUrl: '/Bakery/4.jpg',
    barcode: '8904043900177',
    brand: 'Britannia',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '55',
    name: 'Lina Chocolate Muffin',
    description: 'A soft and moist chocolate chip muffin.',
    price: 89,
    weight: '1 pc',
    category: 'Bakery',
    imageUrl: '/Bakery/5.jpg',
    barcode: '11',
    brand: 'Lina',
    ecologicalScore: 20,
    nutritionalScore: 20
  },
  {
    id: '56',
    name: 'Britannia Gobbles Fruit Cake',
    description: 'A soft and delicious fruit cake slice.',
    price: 20,
    weight: '75 g',
    category: 'Bakery',
    imageUrl: '/Bakery/6.jpg',
    barcode: '8901063365087',
    brand: 'Britannia',
    ecologicalScore: 20,
    nutritionalScore: 20
  },
  {
    id: '57',
    name: 'Pillsbury Milk Choco Spread',
    description: 'Creamy and delicious chocolate spread for bread and rotis.',
    price: 249,
    weight: '350 g',
    category: 'Bakery',
    imageUrl: '/Bakery/7.jpg',
    barcode: '8904150500880',
    brand: 'Pillsbury',
    ecologicalScore: 50,
    nutritionalScore: 30
  },
  {
    id: '58',
    name: 'Winkies Swiss Roll - Chocolate',
    description: 'A delightful chocolate swiss roll for dessert.',
    price: 25,
    weight: '25 g',
    category: 'Bakery',
    imageUrl: '/Bakery/8.jpg',
    barcode: '8906005610935',
    brand: 'Winkies',
    ecologicalScore: 40,
    nutritionalScore: 20
  },
  {
    id: '59',
    name: 'Bagrry\'s Crunchy Muesli with Almonds',
    description: 'A healthy and crunchy breakfast muesli.',
    price: 345,
    weight: '500 g',
    category: 'Bakery',
    imageUrl: '/Bakery/9.jpg',
    barcode: '8902710500776',
    brand: 'Bagrry\'s',
    ecologicalScore: 75,
    nutritionalScore: 75
  },
  {
    id: '60',
    name: 'Elite Softy Sandwich White Bread',
    description: 'Soft and fresh white bread, perfect for sandwiches.',
    price: 45,
    weight: '450 g',
    category: 'Bakery',
    imageUrl: '/Bakery/10.jpg',
    barcode: '8906009991139',
    brand: 'Elite',
    ecologicalScore: 55,
    nutritionalScore: 45
  },
  // Frozen Foods (10 products)

  {
    id: '61',
    name: 'McCain French Fries',
    description: 'Classic shoestring french fries, ready to fry.',
    price: 99,
    weight: '420 g',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/1.jpg',
    barcode: '8906000610053',
    brand: 'McCain',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '62',
    name: 'Amul Vanilla Magic Ice Cream',
    description: 'Creamy and rich vanilla ice cream tub.',
    price: 150,
    weight: '750 ml',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/2.jpg',
    barcode: '8901262173490',
    brand: 'Amul',
    ecologicalScore: 50,
    nutritionalScore: 30
  },
  {
    id: '63',
    name: 'Safal Frozen Green Peas',
    description: 'Fresh green peas, frozen to retain nutrients.',
    price: 135,
    weight: '1 kg',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/3.jpg',
    barcode: '8901722060056',
    brand: 'Safal',
    ecologicalScore: 60,
    nutritionalScore: 85
  },
  {
    id: '64',
    name: 'Kwality Wall\'s Cornetto Double Chocolate',
    description: 'A crunchy cone with a double chocolate treat.',
    price: 60,
    weight: '105 ml',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/4.jpg',
    barcode: '8901030772627',
    brand: 'Kwality Wall\'s',
    ecologicalScore: 50,
    nutritionalScore: 20
  },
  {
    id: '65',
    name: 'Godrej Yummiez Chicken Nuggets',
    description: 'Crispy and juicy chicken nuggets, ready to cook.',
    price: 265,
    weight: '500 g',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/5.jpg',
    barcode: '8902756431157',
    brand: 'Godrej Yummiez',
    ecologicalScore: 30,
    nutritionalScore: 40
  },
  {
    id: '66',
    name: 'ITC Master Chef Veggie Pizza Pockets',
    description: 'Pizza pockets filled with veggies and cheese.',
    price: 99,
    weight: '160 g',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/6.jpg',
    barcode: '8906065169695',
    brand: 'ITC Master Chef',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '67',
    name: 'Prasuma Original Chicken Momos',
    description: 'Authentic Himalayan style chicken momos.',
    price: 285,
    weight: '24 pcs',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/7.jpg',
    barcode: '8906107170207',
    brand: 'Prasuma',
    ecologicalScore: 45,
    nutritionalScore: 40
  },
  {
    id: '68',
    name: 'Amul Malai Paneer Cubes - Frozen',
    description: 'Soft paneer cubes, frozen for longer shelf life.',
    price: 90,
    weight: '200 g',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/8.jpg',
    barcode: '8901262180016',
    brand: 'Amul',
    ecologicalScore: 40,
    nutritionalScore: 65
  },
  {
    id: '69',
    name: 'Baskin Robbins Mississippi Mud Ice Cream',
    description: 'Decadent chocolate fudge and brownie ice cream.',
    price: 325,
    weight: '500 ml',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/9.jpg',
    barcode: '8906006852457',
    brand: 'Baskin Robbins',
    ecologicalScore: 35,
    nutritionalScore: 25
  },
  {
    id: '70',
    name: 'Sumeru Classique Sweet Corn',
    description: 'Juicy and sweet corn kernels, frozen fresh.',
    price: 75,
    weight: '400 g',
    category: 'Frozen Foods',
    imageUrl: '/Frozen-foods/10.jpg',
    barcode: '8901688908124',
    brand: 'Sumeru',
    ecologicalScore: 60,
    nutritionalScore: 80
  },
  // Household Essentials (10 products)
 {
    id: '71',
    name: 'Harpic Powerplus Toilet Cleaner',
    description: 'Disinfectant toilet cleaner that kills 99.9% of germs.',
    price: 93,
    weight: '500 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/1.jpg',
    barcode: '8901396151005',
    brand: 'Harpic',
    ecologicalScore: 20,
    nutritionalScore: null
  },
  {
    id: '72',
    name: 'Lizol Disinfectant Surface Cleaner',
    description: 'Cleans and disinfects floors and surfaces.',
    price: 98,
    weight: '500 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/2.jpg',
    barcode: '8901396117209',
    brand: 'Lizol',
    ecologicalScore: 40,
    nutritionalScore: null
  },
  {
    id: '73',
    name: 'Vim Dishwash Liquid Gel - Lemon',
    description: 'Powerful dishwash gel that removes tough grease.',
    price: 110,
    weight: '500 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/3.jpg',
    barcode: '8901030962769',
    brand: 'Vim',
    ecologicalScore: 55,
    nutritionalScore: null
  },
  {
    id: '74',
    name: 'Surf Excel Matic Top Load Detergent Powder',
    description: 'Tough stain removal for top load washing machines.',
    price: 250,
    weight: '1 kg',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/4.jpg',
    barcode: '8901030816598',
    brand: 'Surf Excel',
    ecologicalScore: 30,
    nutritionalScore: null
  },
  {
    id: '75',
    name: 'Comfort After Wash Fabric Conditioner',
    description: 'Leaves clothes soft, smooth, and fragrant.',
    price: 230,
    weight: '860 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/5.jpg',
    barcode: '8909106022003',
    brand: 'Comfort',
    ecologicalScore: 35,
    nutritionalScore: null
  },
  {
    id: '76',
    name: 'Good Knight Gold Flash Liquid Vapourizer',
    description: 'Protects from mosquitoes for a peaceful sleep.',
    price: 85,
    weight: '45 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/6.jpg',
    barcode: '8901023022951',
    brand: 'Good Knight',
    ecologicalScore: 15,
    nutritionalScore: null
  },
  {
    id: '77',
    name: 'Presto! 2 Ply Kitchen Tissue Roll',
    description: 'Absorbent kitchen towels for spills and cleaning.',
    price: 79,
    weight: '60 pulls',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/7.jpg',
    barcode: '12',
    brand: 'Presto!',
    ecologicalScore: 60,
    nutritionalScore: null
  },
  {
    id: '78',
    name: 'Colin Glass and Surface Cleaner',
    description: 'Provides a streak-free shine on glass and surfaces.',
    price: 93,
    weight: '500 ml',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/8.jpg',
    barcode: '8901396461005',
    brand: 'Colin',
    ecologicalScore: 40,
    nutritionalScore: null
  },
  {
    id: '79',
    name: 'Scotch-Brite Scrub Sponge',
    description: 'Sponge with a scrub pad for easy dishwashing.',
    price: 45,
    weight: '1 pc',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/9.jpg',
    barcode: '8901361303842',
    brand: 'Scotch-Brite',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  {
    id: '80',
    name: 'Ariel Matic Front Load Detergent Powder',
    description: 'Tough stain removal for front load machines.',
    price: 275,
    weight: '1 kg',
    category: 'Household Essentials',
    imageUrl: '/Household-essentials/10.jpg',
    barcode: '4987176174963',
    brand: 'Ariel',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  // Personal Care (10 products)
 {
    id: '81',
    name: 'Colgate MaxFresh Toothpaste',
    description: 'Cooling crystals for intense freshness and cavity protection.',
    price: 98,
    weight: '150 g',
    category: 'Personal Care',
    imageUrl: '/Personal-care/1.jpg',
    barcode: '8901314847294',
    brand: 'Colgate',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  {
    id: '82',
    name: 'Dove Cream Beauty Bathing Bar',
    description: 'Moisturizing bar for soft and smooth skin.',
    price: 62,
    weight: '125 g',
    category: 'Personal Care',
    imageUrl: '/Personal-care/2.jpg',
    barcode: '8901030824630',
    brand: 'Dove',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  {
    id: '83',
    name: 'Head & Shoulders Cool Menthol Shampoo',
    description: 'Anti-dandruff shampoo with a cooling menthol feel.',
    price: 185,
    weight: '180 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/3.jpg',
    barcode: '4902430774147',
    brand: 'Head & Shoulders',
    ecologicalScore: 40,
    nutritionalScore: null
  },
  {
    id: '84',
    name: 'Dettol Original Germ Protection Handwash',
    description: 'Protects from 100 illness-causing germs.',
    price: 99,
    weight: '200 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/4.jpg',
    barcode: '8901396389699',
    brand: 'Dettol',
    ecologicalScore: 65,
    nutritionalScore: null
  },
  {
    id: '85',
    name: 'Nivea Soft Light Moisturizer Cream',
    description: 'A light and non-greasy moisturizer for face and body.',
    price: 175,
    weight: '100 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/5.jpg',
    barcode: '4005808679829',
    brand: 'Nivea',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  {
    id: '86',
    name: 'Gillette Mach3 Turbo Manual Shaving Razor',
    description: 'Closer shave, without all the irritation.',
    price: 250,
    weight: '1 pc',
    category: 'Personal Care',
    imageUrl: '/Personal-care/6.jpg',
    barcode: '4987176286833',
    brand: 'Gillette',
    ecologicalScore: 20,
    nutritionalScore: null
  },
  {
    id: '87',
    name: 'Parachute Advansed Aloe Vera Coconut Hair Oil',
    description: 'Coconut oil enriched with Aloe Vera for soft hair.',
    price: 140,
    weight: '250 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/7.jpg',
    barcode: '8901088210409',
    brand: 'Parachute',
    ecologicalScore: 40,
    nutritionalScore: null
  },
  {
    id: '88',
    name: 'Fiama Gel Bar - Blackcurrant & Bearberry',
    description: 'Uplifting and refreshing gel bathing bar.',
    price: 150,
    weight: '3x125 g',
    category: 'Personal Care',
    imageUrl: '/Personal-care/8.jpg',
    barcode: '8901725921545',
    brand: 'Fiama',
    ecologicalScore: 65,
    nutritionalScore: null
  },
  {
    id: '89',
    name: 'Listerine Cool Mint Mouthwash',
    description: 'Fights germs that cause bad breath, plaque, and gingivitis.',
    price: 145,
    weight: '250 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/9.jpg',
    barcode: '8901012133057',
    brand: 'Listerine',
    ecologicalScore: 40,
    nutritionalScore: null
  },
  {
    id: '90',
    name: 'Savlon Antiseptic Liquid',
    description: 'Effective antiseptic liquid for first aid and personal use.',
    price: 95,
    weight: '100 ml',
    category: 'Personal Care',
    imageUrl: '/Personal-care/10.jpg',
    barcode: '8901725973124',
    brand: 'Savlon',
    ecologicalScore: 30,
    nutritionalScore: null
  },
  // Baby (10 products)
  {
    id: '91',
    name: 'Pampers All-Round Protection Diaper Pants (M)',
    description: 'Medium size diaper pants with aloe vera lotion.',
    price: 799,
    weight: '56 pcs',
    category: 'Baby',
    imageUrl: '/Baby/1.jpg',
    barcode: '4987176210845',
    brand: 'Pampers',
    ecologicalScore: 20,
    nutritionalScore: null
  },
  {
    id: '92',
    name: 'Johnson\'s Baby Powder Natural',
    description: 'Classic baby powder to keep skin soft and dry.',
    price: 230,
    weight: '400 g',
    category: 'Baby',
    imageUrl: '/Baby/2.jpg',
    barcode: '8901212100516',
    brand: 'Johnson\'s',
    ecologicalScore: 65,
    nutritionalScore: null
  },
  {
    id: '93',
    name: 'Himalaya Gentle Baby Wipes',
    description: 'Soft and gentle wipes with the goodness of Aloe Vera.',
    price: 195,
    weight: '72 pcs',
    category: 'Baby',
    imageUrl: '/Baby/3.jpg',
    barcode: '8901138513184',
    brand: 'Himalaya',
    ecologicalScore: 35,
    nutritionalScore: null
  },
  {
    id: '94',
    name: 'Johnson\'s No More Tears Baby Shampoo',
    description: 'Gentle shampoo that is mild to the eyes.',
    price: 425,
    weight: '500 ml',
    category: 'Baby',
    imageUrl: '/Baby/4.jpg',
    barcode: '8901012116944',
    brand: 'Johnson\'s',
    ecologicalScore: 50,
    nutritionalScore: null
  },
  {
    id: '95',
    name: 'Nestle Cerelac Wheat-Rice Mixed Fruit Cereal',
    description: 'Nutritious and tasty baby cereal for stage 3.',
    price: 345,
    weight: '300 g',
    category: 'Baby',
    imageUrl: '/Baby/5.jpg',
    barcode: '8901058867541',
    brand: 'Nestle',
    ecologicalScore: 35,
    nutritionalScore: 75
  },
  {
    id: '96',
    name: 'Himalaya Baby Massage Oil',
    description: 'Enriched with Olive Oil and Winter Cherry for nourishment.',
    price: 210,
    weight: '200 ml',
    category: 'Baby',
    imageUrl: '/Baby/6.jpg',
    barcode: '8901138512408',
    brand: 'Himalaya',
    ecologicalScore: 80,
    nutritionalScore: null
  },
  {
    id: '97',
    name: 'MamyPoko Pants Extra Absorb (L)',
    description: 'Large size diapers with up to 12 hours of absorption.',
    price: 999,
    weight: '64 pcs',
    category: 'Baby',
    imageUrl: '/Baby/7.jpg',
    barcode: '8903622003300',
    brand: 'MamyPoko',
    ecologicalScore: 30,
    nutritionalScore: null
  },
  {
    id: '98',
    name: 'Sebamed Baby Rash Cream',
    description: 'Protective cream for preventing and soothing diaper rash.',
    price: 475,
    weight: '100 ml',
    category: 'Baby',
    imageUrl: '/Baby/8.jpg',
    barcode: '4103040019738',
    brand: 'Sebamed',
    ecologicalScore: 65,
    nutritionalScore: null
  },
  {
    id: '99',
    name: 'Chicco Soft Cleansing Baby Wipes',
    description: 'Soft and gentle wipes for sensitive baby skin.',
    price: 249,
    weight: '2x72 pcs',
    category: 'Baby',
    imageUrl: '/Baby/9.jpg',
    barcode: '8058664152520',
    brand: 'Chicco',
    ecologicalScore: 70,
    nutritionalScore: null
  },
  {
    id: '100',
    name: 'Mothercare All We Know Baby Body Wash',
    description: 'Mild and gentle body wash for your baby.',
    price: 299,
    weight: '300 ml',
    category: 'Baby',
    imageUrl: '/Baby/10.jpg',
    barcode: '8904301752007',
    brand: 'Mothercare',
    ecologicalScore: 65,
    nutritionalScore: null
  }
];

// To demonstrate different stores having different items, we'll create a subset for the Kolkata store
const kolkataProducts = allProducts.slice(0, 50).map((p, index) => {
    // Make prices slightly different for demonstration
    const newPrice = p.price + (index % 5);
    return { ...p, price: newPrice };
}).filter(p => p.category !== 'Baby' && p.category !== 'Frozen Foods'); // Let's say Kolkata doesn't stock these yet



export const stores: Store[] = [
  {
    id: 'gurgaon-1',
    name: 'PurePick Gurgaon Central',
    address: 'DLF Phase 4, Gurgaon, Haryana, India',
    latitude: 28.4595,
    longitude: 77.0266,
    products: allProducts,
  },
  {
    id: 'kolkata-1',
    name: 'PurePick Kolkata South',
    address: 'Ballygunge, Kolkata, West Bengal, India',
    latitude: 22.5726,
    longitude: 88.3639,
    products: kolkataProducts,
  },
];
